version: '3'

# TODO port defaults in .properties so we do not need them here
# TODO make server address obsolete: if not specified, use node-id

services:
  n1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n1 --server.address=n1 --server.port=9999 --metadata-port=6000 --replication-port=6050 --storage=/tmp/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
     - 8080:9999
    #env_file: # TODO
      #  - ./.env
  n2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n2 --server.address=n2 --server.port=9999 --metadata-port=6000 --replication-port=6050 --storage=/tmp/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
      - 8081:9999
  n3:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n3 --server.address=n3 --server.port=9999 --metadata-port=6000 --replication-port=6050 --storage=/tmp/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
      - 8082:9999
