version: '3'

# TODO make server address obsolete: if not specified, use node-id

services:
  n1:
    build:
      context: ./
      dockerfile: Dockerfile_debug
    image: raft-log-replication-demo:latest
    command: java -jar /raft-log-replication-demo.jar --node-id=n1 --server.address=n1 --storage=/tmp/raft-demo --peers=n1:6000,n2:6000,n3:6000
    ports:
     - "8080:8000"
  n2:
    build:
      context: ./
      dockerfile: Dockerfile_debug
    image: raft-log-replication-demo:latest
    command: java -jar /raft-log-replication-demo.jar --node-id=n2 --server.address=n2 --storage=/tmp/raft-demo --peers=n1:6000,n2:6000,n3:6000
    ports:
      - "8081:8000"
  n3:
    build:
      context: ./
      dockerfile: Dockerfile_debug
    image: raft-log-replication-demo:latest
    command: java -jar /raft-log-replication-demo.jar --node-id=n3 --server.address=n3 --storage=/tmp/raft-demo --peers=n1:6000,n2:6000,n3:6000
    ports:
      - "8082:8000"
