version: '3'

# TODO make server address obsolete: if not specified, use node-id

# TODO may use string interpolation to insert service id into the commands?

services:
  n1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n1 --server.address=n1 --storage=/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
     - "8080:8000"
    #env_file: # TODO
      #  - ./.env
  n2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n2 --server.address=n2 --storage=/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
      - "8081:8000"
  n3:
    build:
      context: ./
      dockerfile: Dockerfile
    image: raft-log-replication-demo:latest
    command: --node-id=n3 --server.address=n3 --storage=/raft-demo --peers=n1:9999,n2:9999,n3:9999
    ports:
      - "8082:8000"
